### ISSUE TITLE
Related Work

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/autoindex#22]
Please compare https://www.stardog.com/docs/#_indexing_strategy  to autoindex and document the differences in a small section in the README

**Comment by prasanthhs** [comment]
Wild cards(* and ?), Fuzzy search with similarity weights(~) , Proximity Search(~), Term boosting with ^ , boolean searching(AND OR NOT + and -) and term grouping(works automatically when Boolean search is done) has been added in code. I have also added Range Search (For example [Aa TO Bb] or {Aa TO Bb}.  All this code is available under branch Search-customization-with-extra-options. I am looking into Regular expressions and if ES supports them and how.

**Comment by RicardoUsbeck** [comment]
perfectly what we needed
