### ISSUE TITLE
Enable configuring the type of indexed literal

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/autoindex#23]
Currently, we are indexing all rdfs:labels

Make it possible to index also other types of label via a configuration file and via REST webservice at runtime

**Comment by prasanthhs** [comment]
@RicardoUsbeck Do you mean the prefixes or the name of the parameter itself?  Can you please name an example and what input you are looking at from the user for example? Most spraql websites ask the user to type the entire query itself so its a little confusing in this case. 

?type rdfs:label ?label 
prefix.put("rdfs","http://www.w3.org/2000/01/rdf-schema#");

**Comment by RicardoUsbeck** [comment]
What I mean is to replace rdfs:label completely by rdfs:comment for example or to allow indexing rdfs:label and rdfs:comment at the same time. This gives us more flexibility if a new knowledge base uses other properties for instance.  Yes, the SPARQL query would completely change. But see ParameterizedSPARQLQuery in Jena on how to do that on runtime

**Comment by prasanthhs** [comment]
@RicardoUsbeck One quick question about this. Currently we index class, property and entity for a index request. And each of them have different types which get indexed.

For example : Entity has owl:Thing and rdfs:label 
Class has owl:class  and rdfs:label 
Property has rdf:Property and rdfs:label.

Do we allow all these to be editable or just the entity?

**Comment by RicardoUsbeck** [comment]
The second one.

**Comment by prasanthhs** [comment]
@RicardoUsbeck OK there is a small confusion in that. Currently we match label of type rdfs:label. But we also look for "rdf:type" to "owl:Thing" .  If you want to map "rdf:comment" to "rdf:label" for example, then we should allow rdf:type to be editable and not owl:Thing.

The query is 
SELECT DISTINCT  ?key1 ?key2
WHERE
  { ?key1  rdf:type    owl:Thing .
    ?type  rdfs:label  ?key2
  }
LIMIT   10
 The classes and properties are straightforward.

**Comment by prasanthhs** [comment]
Updated in #32
