### ISSUE TITLE
Searching in all categories seems to be not supported

### ISSUE THREAD

**Issue by SiC42** [dice-group/autoindex#28]
Using the HTMl-Interface (http://localhost:9091/query.html), I get results while searching in the "Entity"-category.
However, if I use the 'All'-category, the application throws a *IndexNotFoundException*.

**Comment by prasanthhs** [comment]
@SiC42 Yes i am aware..We don't have a solution for it yet and we are still working on it..

**Comment by prasanthhs** [comment]
fixed with pull request #30.
