### ISSUE TITLE
better documentation in readme

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/autoindex#3]
Please add examples how to add and search for data with autoindex using curl

**Comment by Kunal-Jha** [comment]
Done. Please Review!!

**Comment by RicardoUsbeck** [comment]
Can you please document how to add a new sparql endpoint to the autoindex? apart from that it looks good

**Comment by Kunal-Jha** [comment]
Done !! Will update according to Web Interface once the branch will be merged!!
