### ISSUE TITLE
Running autoindex fails in IDE because of application.properties are not found.

### ISSUE THREAD

**Issue by sajjadpz** [dice-group/autoindex#37]
@prasanthhs 
```
java.io.FileNotFoundException: src/main/resources/application.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
```

At the moment we are using 
```input = new FileInputStream(TEMPLATE_FILE);```

It is good that we use `spring's` way to read the properties and use`Environment` instead of explicitly reading the files.
e.g

```
@Autowired
private Environment env;
```

**Comment by prasanthhs** [comment]
Fixed by pull request #38. 
@sajjadpz Thanks for pointing out the issue. I hope this fixes the issue.
