### ISSUE TITLE
Searching exact URL breaks !! 

### ISSUE THREAD

**Issue by Kunal-Jha** [dice-group/autoindex#5]
The only lead is this but its slow and breaks sometimes https://stackoverflow.com/questions/40806717/elasticsearch-how-to-search-an-url

We need to find a way to query the URL field (if required) !!

**Comment by prasanthhs** [comment]
@RicardoUsbeck I am not sure what we are supposed to be looking for here. Can you please provide some background info on this issue?

**Comment by RicardoUsbeck** [comment]
Searching for exactly this (http://dbpedia.org/resource/Barack_Obama#wife) and getting only the label associated with exactly this resource and not with http://dbpedia.org/resource/Barack or http://dbpedia.org/resource/Obama

**Comment by prasanthhs** [comment]
OK got it. So label search is essentially a partial search Query, more like a wildcard query search But URL search should be exact.

**Comment by RicardoUsbeck** [comment]
a) Try to use  a parameterized (0,1,2) Fuzzyquery please
b) For URIs: The UnitTests will proof it working or not working

**Comment by prasanthhs** [comment]
Fixed but require confirmation of parameters from @RicardoUsbeck
