### ISSUE TITLE
add single surface form for property, class or entity manually

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/autoindex#6]
I need a possibility to enter a single surface form for either a property, class or entity manually /will be assigned to Idrees

**Comment by prasanthhs** [comment]
@RicardoUsbeck Is this issue still open? What does this mean? Search should be on a value (either Label or URL) and everything from property, class or entity should be returned(along with a mention of type)?

**Comment by RicardoUsbeck** [comment]
Yes it is still open. 

In the UI and as REST interface, I need a possibility to insert a single URI-label pair for either a property, class or entity manually to increase search performance.

**Comment by RicardoUsbeck** [comment]
Moreover, searching on either index (class, property, entity, all) via REST should be possible

**Comment by idreestahir** [comment]
@RicardoUsbeck Right now we are getting results for all the Labels against our Endpoint, for instance dbpedia. So if i understood correctly, we should be able to fetch results against **specific label** as well, for instance "Entity or Property" by allowing user to append that label in our Uri or making a separate field in UI to enter the required label name.

**Comment by RicardoUsbeck** [comment]
a) fetch results given a specific label L (via an own endpoint) against a specific index (entity, property, classes), e.g. searchLabel (String label, String index, String userId)
b) fetch results given a specific URI U (via an own endpoint) against a specific index (entity, property, classes), e.g. searchURI (String uri, String index, String userId)

**Comment by prasanthhs** [comment]
@RicardoUsbeck  Sorry to interrupt. Is there a requirement to also fetch a label or uri against all class, entity or property or vice versa fetch all label uri under a particular class entity property? Or is it sufficient to satisfy search as you have mentioned above?

**Comment by RicardoUsbeck** [comment]
You are right:
a) fetch results given a specific label L (via an own endpoint) against a specific index (entity, property, classes) or all indices, e.g. searchLabel (String label, List<String> index, String userId)
b) fetch results given a specific URI U (via an own endpoint) against a specific index (entity, property, classes) or all indices, e.g. searchURI (String uri,  List<String> index, String userId)

**Comment by prasanthhs** [comment]
Manually fetching by Specific Label or URL against specific index or all Indices is supported(Pull Request #21). 

Indexing of a single URI,Label pair is still pending and @idreestahir will be working on the same.

**Comment by prasanthhs** [comment]
Works fine. Can be closed.  Searching against all Indices requires some investigation of ES. Will be taken up as separate requirement

**Comment by guru5590** [comment]
U can try creating an "Alias" on Elasticsearch indicies....this should help
query multiple indicies.
