### ISSUE TITLE
Dockerizing Auto Index

### ISSUE THREAD

**Issue by idreestahir** [dice-group/autoindex#8]

**Comment by idreestahir** [comment]
Dockerized the project. Now working on Volumes.

**Comment by idreestahir** [comment]
@yamalight  @prasanthhs 
I request for your review on this docker implementation.

**Comment by yamalight** [comment]
I couldn't make the docker image work - it just gets stuck on "Loading data" for me.

A few comments on docs side:
- I don't see any docs w.r.t. volumes usage
- Readme currently mentions a way to build image yourself, but not that you can pull it from hub using: `docker run dicegroup/autoindex`

**Comment by idreestahir** [comment]
*Hi Tim.*
Thanks for the feedback.
I've updated read me while I'm finalizing section of volumes. The reason it
is stuck on Loading Data is because we are fetching all instances from our
end point and it takes quite time to load data.


*Regards*
*Idrees Tahir*

**Comment by yamalight** [comment]
OK, if you are sure it works, then aside from my comments on docs - everything seems to be OK. 👍

**Comment by prasanthhs** [comment]
Everything seems to be OK. Closing this.
